version: "3.7"
services:
  # react-dev service
  react-dev:
    # service container name
    container_name: react-dev
    build:
      # looks for Dockerfile in current directory
      context: .
      # the dockerfile to be run
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Folders outside of Docker that are to be used by Docker
    volumes:
      - ".:/app"
      - "/app/node_modules"
    # set dev mode
    environment:
      - NODE_ENV=development
